import { readFile } from "node:fs/promises";

const requiredFiles = [
  "index.html",
  "styles.css",
  "app.js",
  "manifest.webmanifest",
  "sw.js",
  "schema.sql",
  "README.md",
  "server.js",
  ".env.example",
  "lib/api-providers.mjs"
];

const contents = Object.fromEntries(
  await Promise.all(requiredFiles.map(async (file) => [file, await readFile(file, "utf8")]))
);

const assertions = [
  ["index links stylesheet", contents["index.html"].includes('href="./styles.css"')],
  ["index loads app module", contents["index.html"].includes('src="./app.js"')],
  ["index initializes tabbar hidden", contents["index.html"].includes('id="appTabbar"') && contents["index.html"].includes("hidden")],
  ["app has auth token refresh", contents["app.js"].includes("refreshFcmToken")],
  ["app toggles tabbar hidden state", contents["app.js"].includes("appTabbar.hidden = !user")],
  ["app calls runtime config API", contents["app.js"].includes("/api/config")],
  ["app calls medicine API", contents["app.js"].includes("/api/medicine/search")],
  ["app calls OCR API", contents["app.js"].includes("/api/ocr")],
  ["app calls pharmacy API", contents["app.js"].includes("/api/pharmacies")],
  ["app calls hospital API", contents["app.js"].includes("/api/hospitals")],
  ["app uses direct camera capture for OCR", contents["app.js"].includes("navigator.mediaDevices.getUserMedia") && contents["app.js"].includes("ocrCameraPreview") && contents["app.js"].includes("captureOcrButton")],
  ["app does not present OCR as image upload", !contents["app.js"].includes('id="ocrImage" type="file"')],
  ["app labels OCR as medicine registration", contents["app.js"].includes("OCR 약 등록") && contents["app.js"].includes("복약 스케줄에 등록합니다")],
  ["app starts with empty OCR text", contents["app.js"].includes('ocrText: ""')],
  ["app runs OCR after camera capture", contents["app.js"].includes("#captureOcrButton") && contents["app.js"].includes("촬영 이미지를 OCR로 분석 중입니다.")],
  ["app upscales OCR images before upload", contents["app.js"].includes("prepareImageForOcrDataUrl") && contents["app.js"].includes("Math.max(1600, image.naturalWidth)")],
  ["app can stop OCR camera stream", contents["app.js"].includes("stopOcrCamera") && contents["app.js"].includes("track.stop()")],
  ["app has API status display", contents["app.js"].includes("renderApiStatus")],
  ["app has Kakao SDK hook", contents["app.js"].includes("loadKakaoMapSdk")],
  ["app distinguishes current location and store marker types on Kakao map", contents["app.js"].includes("createKakaoMapMarker") && contents["app.js"].includes('type: "user"') && contents["app.js"].includes("kakaoMarkerLabel") && ["user", "pharmacy", "hospital", "store"].every((type) => contents["styles.css"].includes(`.kakao-place-marker--${type}`))],
  ["app lets users close Kakao store detail overlays", contents["app.js"].includes("closeActiveStoreDetail") && contents["app.js"].includes("activeStoreDetail === detailOverlay") && contents["app.js"].includes("kakao-store-detail__close")],
  ["app shows status and address in Kakao marker details", contents["app.js"].includes("kakao-store-detail__status") && contents["app.js"].includes("kakao-store-detail__address") && contents["app.js"].includes('place.address || "주소 없음"')],
  ["app explains Kakao map local service setup", contents["app.js"].includes("카카오맵/로컬 서비스 활성화")],
  ["app hides fallback map pins when live Kakao map is configured", contents["app.js"].includes("shouldRenderFallbackPins")],
  ["app has OCR matching", contents["app.js"].includes("extractMedicines")],
  ["app has schedule table shape", contents["app.js"].includes("dosage_times")],
  ["app has map guidance", contents["app.js"].includes("map.kakao.com")],
  ["app centers live map on current geolocation", contents["app.js"].includes("currentPosition: null") && contents["app.js"].includes("state.currentPosition") && contents["app.js"].includes("내 위치")],
  ["app asks for location permission on every app launch", contents["app.js"].includes("requestLocationOnAppLaunch") && contents["app.js"].includes("위치 권한 확인 중입니다.")],
  ["CSS defines coral primary", contents["styles.css"].includes("--primary: #ff7b68")],
  ["SQL defines users", contents["schema.sql"].includes("create table if not exists public.users")],
  ["SQL defines medication schedules", contents["schema.sql"].includes("create table if not exists public.medication_schedules")],
  ["SQL defines medicine cache", contents["schema.sql"].includes("create table if not exists public.medicine_cache")],
  ["SQL excludes safe store list", !contents["schema.sql"].includes("safe_store_list")],
  ["SQL enables users RLS", contents["schema.sql"].includes("alter table public.users enable row level security")],
  ["SQL allows users own insert", contents["schema.sql"].includes('create policy "users_insert_own"')],
  ["server exposes config route", contents["server.js"].includes('url.pathname === "/api/config"')],
  ["providers include OpenRouter OCR", contents["lib/api-providers.mjs"].includes("OPENROUTER_CHAT_URL")],
  ["providers use current OpenRouter free vision router", contents["lib/api-providers.mjs"].includes('DEFAULT_OPENROUTER_OCR_MODEL = "openrouter/free"')],
  ["providers retry retired OpenRouter OCR models", contents["lib/api-providers.mjs"].includes("openRouterOcrModelCandidates")],
  ["providers explain OpenRouter OCR rate limits", contents["lib/api-providers.mjs"].includes("OpenRouter 무료 OCR 사용량 제한입니다.")],
  ["app excludes Kakao login mock", !contents["app.js"].includes("kakaoMockButton")],
  ["app excludes demo login", !contents["app.js"].includes("startDemoSession")],
  ["app excludes install app action", !contents["app.js"].includes("installAppButton")],
  ["app requests signup verification email", contents["app.js"].includes("/api/auth/signup-code")],
  ["app preserves pending signup credentials", contents["app.js"].includes("pendingSignup?.password")],
  ["app validates signup password confirmation", contents["app.js"].includes("비밀번호 확인이 일치하지 않습니다.")],
  ["app rejects blank-only passwords", contents["app.js"].includes("비밀번호를 입력하세요.")],
  ["app rejects passwords containing spaces", contents["app.js"].includes("비밀번호에는 공백을 사용할 수 없습니다.")],
  ["app requires signup terms agreement", contents["app.js"].includes("필수 약관에 동의해야 회원가입할 수 있습니다.")],
  ["app submits signup verification code", contents["app.js"].includes("verificationCode: normalizeVerificationCode(verificationCode)")],
  ["app resets signup verification after missing server code", contents["app.js"].includes("isSignupCodeResetRequired") && contents["app.js"].includes("pendingSignup = null")],
  ["app blocks invalid schedule date range", contents["app.js"].includes("종료일은 시작일보다 빠를 수 없습니다.")],
  ["app blocks taking zero remaining pills", contents["app.js"].includes("남은 약이 0개라 복용 체크를 할 수 없습니다.")],
  ["app supports store phone calls", contents["app.js"].includes("tel:${phone}")],
  ["app renders store open/closed status", contents["app.js"].includes("storeStatusLabel") && contents["app.js"].includes("영업 종료") && contents["styles.css"].includes(".badge.closed")],
  ["app supports nickname profile edits", contents["app.js"].includes("닉네임을 저장했습니다.")],
  ["app blocks direct email profile edits", contents["app.js"].includes("이메일 변경은 추가 인증이 필요해 현재 제한됩니다.")],
  ["app handles expired sessions", contents["app.js"].includes("만료된 세션입니다. 다시 로그인하세요.")],
  ["app shows offline network state", contents["app.js"].includes("오프라인 상태입니다. 저장 작업은 로컬 대기열에 보관됩니다.")],
  ["app supports password reset email requests", contents["app.js"].includes("/api/auth/password-reset-code")],
  ["app handles unknown password reset email", contents["app.js"].includes("가입 정보가 없는 이메일입니다.")],
  ["app supports password changes", contents["app.js"].includes("비밀번호를 변경했습니다.")],
  ["app blocks reusing the same password", contents["app.js"].includes("기존과 동일한 비밀번호는 사용할 수 없습니다.")],
  ["app rejects invalid auth tokens", contents["app.js"].includes("잘못된 토큰입니다. 다시 로그인하세요.")],
  ["app recovers Supabase unconfirmed email accounts", contents["app.js"].includes("Supabase 이메일 미확인 계정입니다. 방금 보낸 인증코드를 입력하면 앱 계정을 복구합니다.")],
  ["app creates local auth user for Supabase already registered recovery", contents["app.js"].includes("makeLocalAuthUser") && contents["app.js"].includes("isAlreadyRegisteredAuthError")],
  ["app shows similar medicine candidates", contents["app.js"].includes("유사한 약 후보")],
  ["app uses typo distance for similar medicine candidates", contents["app.js"].includes("levenshteinDistance") && contents["app.js"].includes("medicineNameSimilarity")],
  ["app shows typo candidates before remote medicine search", contents["app.js"].includes("const exactMedicine = lookupMedicine(query);") && contents["app.js"].includes("if (!exactMedicine && candidates.length) {")],
  ["app limits similar medicine candidates to top 3", contents["app.js"].includes("slice(0, 3)")],
  ["app renders even one similar medicine candidate", contents["app.js"].includes("candidates.length > 0 ? renderMedicineCandidates(candidates)")],
  ["app supports selecting one medicine from candidates", contents["app.js"].includes("data-select-medicine")],
  ["app sorts stores by distance", contents["app.js"].includes("sortStoresByDistance")],
  ["app limits visible nearby stores to 20", contents["app.js"].includes("MAX_VISIBLE_STORES")],
  ["app requests no more than 20 public-data stores", contents["app.js"].includes("new URLSearchParams({ limit: String(MAX_VISIBLE_STORES) })")],
  ["app filters nearby stores within 3km when location is known", contents["app.js"].includes("NEARBY_RADIUS_KM")],
  ["app falls back to unfiltered API results when nearby filter would hide everything", contents["app.js"].includes("fallbackToUnfilteredStores")],
  ["app keeps convenience store fallback when live APIs do not provide stores", contents["app.js"].includes("convenienceStoreFallback")],
  ["app searches nearby real places with Kakao Places", contents["app.js"].includes("loadNearbyKakaoPlaces") && contents["app.js"].includes("keywordSearch") && contents["app.js"].includes("kakao.maps.services.Places")],
  ["app retrieves a second Kakao Places page to fill 20 results", contents["app.js"].includes("searchKakaoKeywordPage") && contents["app.js"].includes("searchKakaoKeywordPage(places, keyword, type, center, 2)")],
  ["app enriches nearby Kakao pharmacies with public operating hours", contents["app.js"].includes("loadPublicStoreHoursForCurrentRegion") && contents["app.js"].includes("mergeKakaoStoreHours") && contents["app.js"].includes("coord2RegionCode")],
  ["providers can enrich missing store hours with BUSINESS_HOURS_API", contents["lib/api-providers.mjs"].includes("businessHoursApi: env.BUSINESS_HOURS_API") && contents["lib/api-providers.mjs"].includes("enrichStoresWithBusinessHours") && contents["lib/api-providers.mjs"].includes("buildGooglePlacesHoursUrl") && contents[".env.example"].includes("BUSINESS_HOURS_API=")],
  ["app searches nearby convenience stores with Kakao Places", contents["app.js"].includes("편의점") && contents["app.js"].includes("normalizeKakaoPlace")],
  ["app refresh invalidates Kakao nearby search cache", contents["app.js"].includes("resetNearbyKakaoSearch") && contents["app.js"].includes("state.kakaoNearbySearchKey = \"\"")],
  ["app supports region map search", contents["app.js"].includes("regionSearchInput")],
  ["app does not hardcode map API region to Seoul Jung-gu", !contents["app.js"].includes('region1=서울특별시&region2=중구')],
  ["app supports store name map search", contents["app.js"].includes("storeSearchInput")],
  ["app shows no map search results", contents["app.js"].includes("검색 조건에 맞는 판매처가 없습니다.")],
  ["app shows no nearby pharmacy results", contents["app.js"].includes("반경 3km 이내 판매처가 없습니다.")],
  ["app shows missing store hours as unknown", contents["app.js"].includes("영업정보 없음")],
  ["app does not mark stores with missing hours as open", contents["app.js"].includes('statusLabel: "영업정보 없음"') && contents["app.js"].includes("open: false")],
  ["app recalculates store open status from visible hours at render time", contents["app.js"].includes("currentStoreStatus") && contents["app.js"].includes("storeStatusFromHours(storeHoursLabel(store), now)") && contents["app.js"].includes("String(hours).includes(\"24시간\")")],
  ["app refreshes visible store status badges without remounting the map", contents["app.js"].includes("refreshRenderedStoreStatuses") && contents["app.js"].includes("data-store-status-id") && contents["app.js"].includes("badge.className = `badge ${storeStatusClass(status)}`")],
  ["app shows persistent location permission denial hint", contents["app.js"].includes("locationPermissionDenied") && contents["app.js"].includes("위치 권한을 허용해주세요")],
  ["app prioritizes convenience stores on holidays", contents["app.js"].includes("공휴일에는 상비약 판매 편의점을 우선 안내합니다.")],
  ["app supports editing schedule times", contents["app.js"].includes("data-edit-schedule")],
  ["app supports editing schedule date range", contents["app.js"].includes("스케줄 수정 완료")],
  ["app handles camera permission denial", contents["app.js"].includes("카메라 권한이 필요합니다.")],
  ["app shows unmatched OCR medicine candidates", contents["app.js"].includes("ocrCandidateMedicines") && contents["app.js"].includes("OCR에서 추출한 후보입니다.")],
  ["app persists newly fetched medicines", contents["app.js"].includes("persistMedicineCache")],
  ["app queues offline schedule saves", contents["app.js"].includes("pending_mutations")],
  ["app stores FCM tokens per device", contents["app.js"].includes("fcm_tokens") && contents["schema.sql"].includes("user_fcm_tokens")],
  ["app calculates store distance from current geolocation", contents["app.js"].includes("formatStoreDistance") && contents["app.js"].includes("haversineDistanceKm") && contents["app.js"].includes("거리 확인 전")],
  ["app documents concurrent login as allowed", contents["app.js"].includes("동시 로그인 허용")],
  ["app deactivates accounts instead of deleting", contents["app.js"].includes("is_active = false") && contents["app.js"].includes("deleted_at")],
  ["app blocks deactivated account login", contents["app.js"].includes("탈퇴 처리된 계정은 로그인할 수 없습니다.")],
  ["app confirms schedule deletion", contents["app.js"].includes("스케줄을 삭제했습니다.")],
  ["app prevents duplicate dose checks", contents["app.js"].includes("이미 오늘 복용 기록이 있습니다.")],
  ["app blocks missing medicine names", contents["app.js"].includes("약 이름을 입력하세요.")],
  ["app lets users type schedule medicine names directly", contents["app.js"].includes('id="scheduleMedicine" type="text"') && !contents["app.js"].includes('<select id="scheduleMedicine"')],
  ["app shows no result for unknown schedule medicine names", contents["app.js"].includes("입력한 약을 찾을 수 없습니다. 검색 결과 없음")],
  ["app blocks more than five dose times", contents["app.js"].includes("하루 최대 5회까지 등록할 수 있습니다.")],
  ["app blocks duplicate dose times", contents["app.js"].includes("복용 시간이 중복되었습니다.")],
  ["app blocks remaining pill counts over 999", contents["app.js"].includes("남은 알약 수는 999개 이하로 입력하세요.")],
  ["app blocks duplicate medicine schedules per user", contents["app.js"].includes("이미 등록된 약입니다.")],
  ["app supports morning lunch evening time presets", contents["app.js"].includes('data-time-preset="13:00"') && contents["app.js"].includes('data-time-preset="19:00"')],
  ["app supports per-dose amount", contents["app.js"].includes("dose_amount") && contents["app.js"].includes("1회 복용량")],
  ["app supports missed dose records", contents["app.js"].includes("미복용 기록")],
  ["app stores dose records by date", contents["app.js"].includes("dose_records")],
  ["app stores dose records by date and time slot", contents["app.js"].includes("dose_time") && contents["app.js"].includes("currentDoseSlot")],
  ["app renders dose history", contents["app.js"].includes("renderDoseHistory")],
  ["app renders adherence rate", contents["app.js"].includes("복약 성공률")],
  ["app keeps due reminders separate from the notice card", contents["app.js"].includes("in_app_notifications") && !contents["app.js"].includes("복용 시간이 도달한 알림입니다.")],
  ["app shows upcoming reminders in the notice card", contents["app.js"].includes("renderUpcomingReminderNotice") && contents["app.js"].includes("곧 복용할 예정입니다.") && contents["app.js"].includes("upcomingReminderNotices")],
  ["app catches missed reminder checks after the exact minute passes", contents["app.js"].includes("dueReminderTimes") && contents["app.js"].includes("toMinutes(time) <= currentMinutes")],
  ["app does not issue a due reminder before the scheduled time", contents["app.js"].includes("currentMinutes - doseMinutes <= REMINDER_GRACE_MINUTES")],
  ["app logs notification failures", contents["app.js"].includes("notification_failures") && contents["app.js"].includes("알림 발송 실패 로그")],
  ["server normalizes pasted verification codes", contents["server.js"].includes("normalizeVerificationCode")],
  ["server sends signup verification email", contents["server.js"].includes('url.pathname === "/api/auth/signup-code"')],
  ["server sends password reset email", contents["server.js"].includes('url.pathname === "/api/auth/password-reset-code"')],
  ["server falls back after verified signup rate limits", contents["server.js"].includes("canFallbackAfterVerifiedSignup") && contents["server.js"].includes("Supabase 인증 요청 제한으로 앱 로컬 계정으로 가입을 완료했습니다.")],
  ["server returns extracted OCR name candidates", contents["server.js"].includes("extractMedicineNameCandidates") && contents["server.js"].includes("extracted_names")],
  ["app surfaces Kakao map errors", contents["app.js"].includes("renderMapStatus")]
];

const failures = assertions.filter(([, passed]) => !passed);

if (failures.length > 0) {
  for (const [name] of failures) {
    console.error(`FAIL ${name}`);
  }
  process.exit(1);
}

for (const [name] of assertions) {
  console.log(`PASS ${name}`);
}
